FuelLabs/data-systems

- Cargo.toml
- crates/nats-stream/Cargo.toml
⭐  Closes #10 
The idea here is lock all dependencies in minor instead of patch to avoid an extra step when getting security updates.
> ci: lock versions on minor instead of patch

- CONTRIBUTING.md
A typo fix but also a test run of the current state of our local and CI workflows
> docs(repo): fix typo by renaming 'master' to 'main'

- Cargo.lock
- Cargo.toml
- crates/fuel-core-nats/Cargo.toml
- crates/fuel-core-nats/nats.conf
- crates/fuel-core-nats/src/lib.rs
- crates/fuel-core-nats/src/main.rs
Closes #26 
After `3548979` blocks:
```
nats str ls
╭──────────────────────────────────────────────────────────────────────────────╮
│                                    Streams                                   │
├──────┬─────────────┬─────────────────────┬───────────┬────────┬──────────────┤
│ Name │ Description │ Created             │ Messages  │ Size   │ Last Message │
├──────┼─────────────┼─────────────────────┼───────────┼────────┼──────────────┤
│ fuel │             │ 2024-06-12 16:59:04 │ 7,111,105 │ 12 GiB │ 3m9s         │
╰──────┴─────────────┴─────────────────────┴───────────┴────────┴──────────────╯
```
```
nats sub "receipts.>" --last
11:29:28 Subscribing to JetStream Stream holding messages with subject receipts.> starting with the last message received
[#1] Received …
```
> feat(data-stream): bootstrap the stream from Fuel node's storage

- .commitlintrc.yaml
- .github/workflows/ci.yaml
This will enable Dependabot to commit using it's standard `build(deps):` commit format.
> ci(repo): adjust commitlint to enable dependabot

- Makefile
- docker/docker-compose.yml
- docker/fuel-core-nats.Dockerfile
Alongside the Dockerfile for `fuel-core-nats`, this PR:
- re-purposes docker-compose for starting and stopping all services in this repo
- Adds some Makefile script aliases to manage(start/stop) all services or simply manage each service in isolation.
> build(repo): introduce Docker image for `fuel-core-nats`

- docker/docker-compose.yml
This PR ensures the `nats.conf` file is referenced in docker-compose to allow replicable behavior with cloud environments. Additionally, it enables persisting the `fuel-core-nats` volume.
> feat(repo): include nats server config in docker-compose

- .github/actions/docker-publish/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/prepare_release.yaml
- .github/workflows/release.yaml
- .github/workflows/update_deps.yaml
- rust-toolchain.toml
References: https://github.com/FuelLabs/data-systems/issues/15
For the `fuel-core-nats` crate, this PR adds jobs for publishing:
- its Docker image
- ~its binaries within the automated Github Release~
- on crates.io
N/B: This is currently failing because we have not set some important credentials. We need: 
- ~`secrets.GITHUB_TOKEN`~ =>  `secrets.REPO_TOKEN`
- `secrets.DOCKER_IO_READ_ONLY_TOKEN`
- ~`secrets.SLACK_WEBHOOK_NOTIFY_BUILD`~
Dev Note: After the workflow test is done, we should revert this commit: https://github.com/FuelLabs/data-systems/commit/a3227c84e0c34e38e64ddb9f704441fbbff89711
> ci(release): Add jobs for publishing `fuel-core-nats` crate and binaries

- crates/fuel-core-nats/src/lib.rs
- crates/fuel-core-nats/src/nats/subjects.rs
Fuel BlockHeight type `to_string()` outputs hexadecimal which is optimized and perfect for their use-case. For our streams, it will be better to store the integer value directly since it will save us a tidbit of compute time when decoding, which will happen more than encoding.
Because of the hexadecimal output, decoding the block height's subject failed as it expected a regular integer, not a hexadecimal. This change fixes this by replacing the `BlockHeight` type with a `u32`.
N/B: This fix also requires re-publishing. So we need to run:`nats str purge 'blocks.*' -f` & `nats str purge 'transactions.*.*.*' -f` right before deploy.
> fix(data-stream): use u32 for block height to avoid hex outputs in block subjects

- crates/fuel-core-nats/src/lib.rs
Currently, we are publishing our subjects and payloads using pretty json. This quickly added up and caused a large ROM consumption in our NATS cluster. For obvious reasons, pretty json is way heavier compared with it's compact equivalent. This change fixes this by only publishing the blocks and transactions serialized to compact json.
> fix(publisher): publish compact json rather than pretty json

- Cargo.lock
- crates/fuel-streams-core/Cargo.toml
- crates/fuel-streams/Cargo.toml
- crates/fuel-streams/src/client/client_impl.rs
- crates/fuel-streams/src/client/types.rs
- tests/Cargo.toml
- tests/tests/client.rs
- tests/tests/conn.rs
- tests/tests/streams.rs
Quickly getting this conflict out the way for https://github.com/FuelLabs/data-systems/issues/97. `fuel-streams` is the end product of our systems so far, so, it would be better to have that detail in the core crate's namespace. This PR does that update.
> refactor(core): keep `fuel-streams` naming consistent

- Cargo.lock
- crates/fuel-streams-publisher/Cargo.toml
- crates/fuel-streams-publisher/src/lib.rs
- crates/fuel-streams-publisher/src/nats.rs
This solution is temporary because our NATS service is running out of storage in the Cluster again. I conducted some tests by using `bincode` for serialization instead of JSON, and found that it reduced the size by 4 times. Additionally, enabling NATS default compression as an option in the stream also helped with the size reduction.
> fix(publisher): temporary solution for nats storage size

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.2

- .changeset/docs_update.md
- .github/workflows/prepare_release.yaml
- knope.toml
The `prepare-release.yml` action throws an error when there's no bump to create a new version. Since we need to bump for a new release to update the documentation in the crates, but we don't have any bump in the three conventional commits, we need to bump manually using changesets (`knope document-change`).
> ci(repo): Adjust knope for manual releases

- .changeset/docs_update.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.5

- docker/fuel-streams-publisher.Dockerfile
Part of DS-59
Fixes `fuel-streams-publisher` container runtime error.
> build(repo): Remove stale nkey env var

- benches/nats-publisher/src/utils/tx.rs
- crates/fuel-streams-core/Cargo.toml
- crates/fuel-streams-core/src/lib.rs
- crates/fuel-streams-core/src/logs/mod.rs
- crates/fuel-streams-core/src/logs/subjects.rs
- crates/fuel-streams-core/src/logs/types.rs
- crates/fuel-streams-core/src/outputs/subjects.rs
- crates/fuel-streams-core/src/transactions/subjects.rs
- crates/fuel-streams-core/src/types.rs
- crates/fuel-streams-publisher/src/lib.rs
- crates/fuel-streams-publisher/src/logs.rs
- crates/fuel-streams-publisher/src/publisher.rs
- crates/fuel-streams-publisher/src/transactions.rs
- crates/fuel-streams/README.md
- tests/src/lib.rs
- tests/tests/publisher.rs
- tests/tests/stream.rs
Since no actual Log type exists in `fuel-core`(only as a polymorphic type in `Receipt`), 
this change introduces an aggregate Log type for improved DX when consuming logs. 
It also makes it consistent when fetching `Logs` to receive an actual `Log` type.
> feat(publisher): Publish logs

- crates/fuel-streams-publisher/src/publisher.rs
This is a small PR which boosts up the multithreaded paralellized sending of multiple streams. Locally on my machine it does lead to a performance boost.
> feat(repo): Parallel publishing of multiple streams (optimization)

- Cargo.lock
- Cargo.toml
- crates/fuel-streams-core/src/stream/stream_impl.rs
- crates/fuel-streams-core/src/transactions/mod.rs
- crates/fuel-streams-core/src/types.rs
- crates/fuel-streams-core/src/utxos/subjects.rs
- crates/fuel-streams-publisher/Cargo.toml
- crates/fuel-streams-publisher/src/inputs.rs
- crates/fuel-streams-publisher/src/lib.rs
- crates/fuel-streams-publisher/src/logs.rs
- crates/fuel-streams-publisher/src/outputs.rs
- crates/fuel-streams-publisher/src/predicates.rs
- crates/fuel-streams-publisher/src/publisher.rs
- crates/fuel-streams-publisher/src/receipts.rs
- crates/fuel-streams-publisher/src/transactions.rs
- crates/fuel-streams-publisher/src/utxos.rs
Closes: https://linear.app/fuel-network/issue/DS-65/predicates-implement-logic-on-core-and-publisher
Currently, it hashes the entire bytecode as the predicate tag. Once the sway team separates the configurable
from the actual bytecode, the tag fn implementation will need an update accordingly.
> feat(publisher): Publish predicates

- Cargo.lock
- benches/data-parser/benches/deserialize.rs
- benches/data-parser/benches/serialize.rs
- crates/fuel-data-parser/Cargo.toml
- crates/fuel-data-parser/src/error.rs
- crates/fuel-data-parser/src/lib.rs
By checking [Rust Serialization Benchmarks](https://david.kolo.ski/rust_serialization_benchmark/), MessagePack seems an excellent alternative that meets our requirements. It's faster than JSON and slower than Postcard, but it supports other languages like Typescript and doesn't need to define schemas like Protobuf.
> feat(data-parser): Change to MessagePack as default serializer

- benches/nats-publisher/src/main.rs
- crates/fuel-streams-core/src/blocks/mod.rs
- crates/fuel-streams-core/src/blocks/types.rs
- crates/fuel-streams-publisher/src/publisher/mod.rs
- crates/fuel-streams-publisher/src/publisher/payloads/blocks.rs
> fix(publisher): Include `transaction_ids` in blocks

- crates/domains/src/transactions/queryable.rs
- services/api/src/server/handlers/macros.rs
- services/api/src/server/handlers/mod.rs
```
/contracts/{contract_id}/transactions
/accounts/{address}/transactions
```
due to missing normalized values in the db
> feat(repo): Added macros for simplifying the endpoints router

- services/dune/src/s3/client.rs
This PR modifies the AWS SDK client to support optionally assuming a specified role. The current iteration assumes that a role will always need to be assumed, which is not always the case.
Also, the current code looks for `AWS_ROLE_ARN`, which is a reserved environment variable name by EKS, so this PR modifies it to `AWS_ASSUME_ROLE_ARN` so it is clear what the intention is when someone uses the value.
> feat(repo): Optional AWS assumable role

- services/publisher/src/metrics.rs
- services/publisher/src/publish.rs
- services/webserver/src/metrics.rs
- services/webserver/src/server/websocket/session.rs
Reducing the cardinality of prometheus metrics down to a usable level. Currently, cardinality on metrics includes the block ID and user IDs, which means we have an exponential explosion of metrics inside monitoring systems.
This means that it is _very_ expensive to collect and report on metrics from this service.
> fix(repo): Reduce metrics cardinality

- services/publisher/src/history.rs
- services/publisher/src/lib.rs
- services/publisher/src/main.rs
This pull request introduces periodic processing of historical gaps in block publishing and refactors the block processing logic to improve efficiency and clarity. Additionally, it integrates the new functionality into the main application workflow and updates module exports.
* [`services/publisher/src/history.rs`](diffhunk://#diff-15afc710ffdc91810773a93ad8ee2802998dbcd10923a1230fdbf52dd756376dR17-R54): Added the `process_historical_gaps_periodically` function to periodically process historical gaps every 5 hours, ensuring shutdown signals are handled gracefully.
* [`services/publisher/src/history.rs`](diffhunk://#diff-15afc710ffdc91810773a93ad8ee2802998dbcd10923a1230fdbf52dd756376dL74-R113): Replaced `process_blocks_with_join_set` with `process_blocks`, removing the use of `JoinSet` and …
> feat(sv-publisher): Add routine to sync historical gaps

- services/consumer/src/executor/block_executor.rs
This pull request refactors the `BlockExecutor` in `services/consumer/src/executor/block_executor.rs` to improve task management and message acknowledgment. The key changes include adjusting task concurrency limits, simplifying the subscription loop, and ensuring message acknowledgment is conditional on successful processing.
* Reduced `MAX_CONCURRENT_TASKS` from 32 to 30 and `BATCH_SIZE` from 100 to 30 to optimize resource usage. (`[services/consumer/src/executor/block_executor.rsL56-R57](diffhunk://#diff-447b500ed8564ef462714e0456a8575d529b6dfdc64d26b85f331ad9474dcc55L56-R57)`)
* Refactored the subscription loop to create a new `JoinSet` for each batch of messages, ensuring tasks are processed and completed sequentially within each batch. …
> fix(sv-consumer): Ensure block is process before act on it and get on next block

- crates/domains/src/infra/db/db_impl.rs
- services/api/src/cli.rs
- services/api/src/config.rs
- services/api/src/server/handlers/api_key.rs
- services/api/src/server/state.rs
- services/publisher/src/cli.rs
- services/publisher/src/main.rs
This pull request introduces support for separate read and write database connections across multiple services, along with some additional configuration improvements. The changes include adding a `read_url` for databases, updating connection pool configurations, and modifying service logic to utilize the new read and write database separation.
* Added a `min_connections` field to `DbConnectionOpts` and updated the default implementation to set a minimum of 2 connections. Updated `PgPoolOptions` to use `min_connections` from the configuration instead of a hardcoded value. (`crates/domains/src/infra/db/db_impl.rs`) [[1]](diffhunk://#diff-4516faa69b5cbfef33757b1ea643ec75c80cad97faf053161a098c4cffeb1b51R63) [[2]](diffhunk://#diff-4516faa69b5cbfef33757b1ea643ec75c80cad97faf053161a098c4cffeb1b51 …
> feat(sv-api): Add read-only database configuration
