FuelLabs/data-systems

- .github/actions/docker-publish/action.yaml
- .github/workflows/docker_publish.yaml
Add Git workflow and action for building and publishing the `fuel-core-nats` Docker image
> feat(release): Publish Docker image

- crates/core/src/nats/client.rs
- crates/core/src/nats/streams.rs
- crates/fuel-core-nats/src/nats.rs
Issue: https://github.com/FuelLabs/data-systems/issues/28
> feat(core): added nats publishing deduplication logic and tests

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams-core/Cargo.toml
- crates/fuel-streams-macros/Cargo.toml
- crates/fuel-streams-macros/subject-derive/Cargo.toml
- crates/fuel-streams/Cargo.toml
- tests/Cargo.toml
> ci(release): Preparing v0.0.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.4

- Cargo.lock
- crates/fuel-data-parser/Cargo.toml
- docker/fuel-streams-publisher.Dockerfile
> build(repo): Upgrade Docker Build's Rust version to 1.79.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.6

- helm/fuel-streams-publisher/Chart.yaml
> ci(repo): Bump helm chart version

- Cargo.lock
- Cargo.toml
This might also help fix the Handshake error
> build(repo): Upgrade `fuel-core` to 0.35

- docker/chain-config/chain_config.json
Another attempt to fix the Handshake errors. 
@pedronauck we will probably need a follow-up task to make this more dynamic 
to allow building for different environments corresponding to the folder layout 
here: https://github.com/FuelLabs/chain-configuration
> fix(repo): Update chain-config

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.7

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.8

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.9

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.10

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.11

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
- examples/Cargo.toml
> ci(release): Preparing v0.0.12

- crates/fuel-streams-publisher/src/publisher/fuel_core_like.rs
- crates/fuel-streams-publisher/src/publisher/mod.rs
- crates/fuel-streams-publisher/src/publisher/payloads/transactions.rs
This will help debug why receipts are not being populated as opposed to just populating with the default empty list
References DS-124
> feat(publisher): Bubble up receipt errors

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
- examples/Cargo.toml
> ci(release): Preparing v0.0.15

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.16

- crates/sv-publisher/src/main.rs
- scripts/run_publisher.sh
Partial fix for the first bug @luizstacio mentioned here: https://fuellabs.slack.com/archives/C06UMEA1FE0/p1735310407287499?thread_ts=1735275546.679239&cid=C06UMEA1FE0
> fix(publisher): Publish in order strictly

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/fuel-streams/Cargo.toml
> ci(release): Preparing v0.0.17

- .github/CODEOWNERS
- Cargo.lock
- Makefile
- Tiltfile
- cluster/charts/fuel-streams/dashboards/api-metrics.json
- cluster/charts/fuel-streams/templates/api/certificate.yaml
- cluster/charts/fuel-streams/templates/api/deployment.yaml
- cluster/charts/fuel-streams/tests/api/certificate_test.yaml
- cluster/charts/fuel-streams/tests/api/deployment_test.yaml
- cluster/charts/fuel-streams/values-local.yaml
- cluster/charts/fuel-streams/values.yaml
- cluster/docker/docker-compose.yml
- cluster/docker/sv-api.Dockerfile
- scripts/run_api.sh
- services/api/Cargo.toml
- services/api/README.md
- services/api/src/cli.rs
- services/api/src/config.rs
- services/api/src/lib.rs
- services/api/src/main.rs
- services/api/src/metrics.rs
- services/api/src/server/errors.rs
- services/api/src/server/handlers/blocks.rs
- services/api/src/server/handlers/mod.rs
- services/api/src/server/mod.rs
- services/api/src/server/state.rs
> feat(repo): Added api service initial skeleton

- Cargo.lock
- crates/domains/Cargo.toml
- crates/domains/src/blocks/queryable.rs
- crates/domains/src/inputs/queryable.rs
- crates/domains/src/outputs/queryable.rs
- crates/domains/src/queryable.rs
- crates/domains/src/receipts/queryable.rs
- crates/domains/src/transactions/queryable.rs
- crates/domains/src/utxos/queryable.rs
- services/api/Cargo.toml
- services/api/src/server/handlers/accounts.rs
- services/api/src/server/handlers/blocks.rs
- services/api/src/server/handlers/contracts.rs
- services/api/src/server/handlers/inputs.rs
- services/api/src/server/handlers/mod.rs
- services/api/src/server/handlers/outputs.rs
- services/api/src/server/handlers/receipts.rs
- services/api/src/server/handlers/transactions.rs
- services/api/src/server/handlers/utxos.rs
> feat(repo): Added api optimizations and improvements

- Cargo.lock
- crates/web-utils/Cargo.toml
- crates/web-utils/src/telemetry/mod.rs
- crates/web-utils/src/telemetry/runtime.rs
- crates/web-utils/src/telemetry/system.rs
Remove system-based metrics from metrics endpoint response
> fix(sv-api): Removed system-based metrics from metrics endpoint

- services/consumer/src/executor/block_executor.rs
This pull request introduces updates to the `BlockExecutor` in `services/consumer/src/executor/block_executor.rs` to improve task processing efficiency and enhance error handling. Key changes include adjustments to batch processing parameters, improved handling of task results, and a new mechanism for gracefully handling unique constraint violations in the database.
* Increased `MAX_CONCURRENT_TASKS` from 30 to 32 and `BATCH_SIZE` from 30 to 100 to allow for more efficient batch processing and concurrency. (`[services/consumer/src/executor/block_executor.rsL56-R57](diffhunk://#diff-447b500ed8564ef462714e0456a8575d529b6dfdc64d26b85f331ad9474dcc55L56-R57)`)
* Refactored the message processing loop to ensure all processing tasks are spawned and completed before moving to the next batch, …
> fix(sv-consumer): Act on messages if db error unique constrains

- services/consumer/src/executor/block_executor.rs
This pull request refines error handling in the `BlockExecutor` implementation and improves logging for unique constraint violations. The changes focus on enhancing code clarity and functionality by introducing more specific error types and improving conditional checks.
* [`services/consumer/src/executor/block_executor.rs`](diffhunk://#diff-447b500ed8564ef462714e0456a8575d529b6dfdc64d26b85f331ad9474dcc55R29): Added `RepositoryError` to the imports to enable more granular error categorization.
* [`services/consumer/src/executor/block_executor.rs`](diffhunk://#diff-447b500ed8564ef462714e0456a8575d529b6dfdc64d26b85f331ad9474dcc55L140-R151): Updated the conditional check in the `BlockExecutor` implementation to handle `Ok` results more explicitly, ensuring that errors within the statistics …
> fix(sv-consumer): Skip when duplicate keys are found on insert

- services/consumer/src/executor/block_executor.rs
This pull request refactors the `BlockExecutor` implementation in `services/consumer/src/executor/block_executor.rs` to simplify task management and improve resource handling. Key changes include replacing `JoinSet` with `tokio::spawn` for task execution, using `OwnedSemaphorePermit` for semaphore management, and restructuring the handling of task results.
* Replaced the `JoinSet` approach with direct use of `tokio::spawn`, simplifying task execution and removing the need for managing a `JoinSet` instance. (`[[1]](diffhunk://#diff-447b500ed8564ef462714e0456a8575d529b6dfdc64d26b85f331ad9474dcc55L98-R106)`, `[[2]](diffhunk://#diff-447b500ed8564ef462714e0456a8575d529b6dfdc64d26b85f331ad9474dcc55L129-R138)`)
* Introduced `OwnedSemaphorePermit` to manage semaphore permits, ensuring proper …
> feat(sv-consumer): Ensure back pressure on block consumer

- cluster/charts/fuel-streams/Chart.yaml
- cluster/charts/fuel-streams/templates/api/deployment.yaml
- cluster/charts/fuel-streams/templates/consumer/deployment.yaml
- cluster/charts/fuel-streams/templates/dune/cronjob.yaml
- cluster/charts/fuel-streams/templates/publisher/statefulset.yaml
- cluster/charts/fuel-streams/templates/webserver/deployment.yaml
- cluster/charts/fuel-streams/values.yaml
Update helm chart - add node affinities
> Update helm chart - add node affinities

- cluster/charts/fuel-streams/Chart.yaml
- cluster/charts/fuel-streams/templates/dune/cronjob.yaml
continuation of #507. I forgot to remove the block which included everything
> fix(fuel-streams):  remove k8s.container-config block
